language: python

python:
  - "3.5"

sudo: required
services:
  - docker

cache:
  - pip
  - directories:
    - node_modules

before_install:
  - docker build -f docker/slim/Dockerfile . -t edxops/credentials:latest
  - make up-test

script:
  # TODO Consider a method that does not rely on git
  - git diff --exit-code -G "^(msgid|msgstr)"
  - make exec-validate

after_success:
  - pip install --upgrade codecov
  - make exec-coverage
  - codecov
