---
CACHES:
    default:
        BACKEND: django.core.cache.backends.memcached.MemcachedCache
        KEY_PREFIX: credentials
        LOCATION:
        - edx.devstack.memcached:11211
CREDENTIALS_SERVICE_USER: credentials_service_user
DATABASES:
    default:
        ATOMIC_REQUESTS: false
        CONN_MAX_AGE: 60
        ENGINE: django.db.backends.mysql
        HOST: edx.devstack.mysql
        NAME: credentials
        PASSWORD: password
        PORT: '3306'
        USER: credentials001
EDX_DRF_EXTENSIONS:
    OAUTH2_USER_INFO_URL: http://edx.devstack.edxapp:18000/oauth2/user_info
EXTRA_APPS:
- credentials.apps.edx_credentials_extensions
FILE_STORAGE_BACKEND:
    DEFAULT_FILE_STORAGE: django.core.files.storage.FileSystemStorage
    MEDIA_ROOT: /edx/var/credentials/media
    MEDIA_URL: /media/
    STATICFILES_STORAGE: django.contrib.staticfiles.storage.ManifestStaticFilesStorage
    STATIC_ROOT: /edx/var/credentials/staticfiles
    STATIC_URL: /static/
JWT_AUTH:
    JWT_ISSUERS:
    -   AUDIENCE: lms-key
        ISSUER: http://edx.devstack.edxapp:18000/oauth2
        SECRET_KEY: lms-secret
LANGUAGE_CODE: en_US.UTF-8
MEDIA_STORAGE_BACKEND:
    DEFAULT_FILE_STORAGE: django.core.files.storage.FileSystemStorage
    MEDIA_ROOT: /edx/var/credentials/media
    MEDIA_URL: /media/
SECRET_KEY: SET-ME-TO-A-UNIQUE-LONG-RANDOM-STRING
SOCIAL_AUTH_EDX_OIDC_ID_TOKEN_DECRYPTION_KEY: credentials-secret
SOCIAL_AUTH_EDX_OIDC_KEY: credentials-key
SOCIAL_AUTH_EDX_OIDC_LOGOUT_URL: http://localhost:18000/logout
SOCIAL_AUTH_EDX_OIDC_PUBLIC_URL_ROOT: http://localhost:18000/oauth2
SOCIAL_AUTH_EDX_OIDC_SECRET: credentials-secret
SOCIAL_AUTH_EDX_OIDC_URL_ROOT: http://edx.devstack.edxapp:18000/oauth2
SOCIAL_AUTH_REDIRECT_IS_HTTPS: false
#STATICFILES_STORAGE: django.contrib.staticfiles.storage.StaticFilesStorage
#STATIC_ROOT: /edx/var/credentials/staticfiles
#TIME_ZONE: UTC
USER_API_URL: http://edx.devstack.edxapp:18000/api/user/v1/
USER_JWT_AUDIENCE: lms-key
USER_JWT_SECRET_KEY: lms-secret
